#!/bin/sh -e
# bemanager
# Boot Environments TUI Manager, wrapper around FreeBSD beadm/bectl utilities.
# A simple utility for manage, backup and restore Boot Environments.
# License: BSD2CLAUSE (BSD 2-clause Simplified License).
# Debug script.
#set -x

# Copyright (c) 2018-2021 José Rivera (JoseMR)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS 'AS IS' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Set environment.
PATH=${PATH}:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# Script version.
VERSION="0.9.6b"

# Must be root.
if [ "$(id -u)" -ne 0 ]; then
	echo "Permission Denied!"
	exit 1
fi

# Display version info.
version()
{
	echo "bemanager ${VERSION}"
}

# Display usage info.
usage()
{
	echo -e "Usage: bemanager [option] [beName | beName@snap | fileName] | [local | remote]
Options:
      -a | --activate  Activate Boot Environment.
      -c | --create    Create Boot Environment.
      -m | --mount     Mount Boot Environment.
      -u | --umount    Unmount Boot Environment.
      -n | --rename    Rename Boot Environment.
      -b | --backup    Backup Boot Environment.
      -r | --restore   Restore Boot Environment.
      -s | --snapshot  Snapshot Boot Environment.
      -d | --destroy   Destroy Boot Environment.
      -v | --version   Display version and exit.
      -h | --help      Display this help message."
}

# Handle special-case commands first.
case "${1}" in
	help|-h|--help)
		usage
		exit 0;;
	version|-v|--version)
		version
		exit 0;;
esac

# Set global variables.
SCRIPTNAME=$(basename $0)
CONFIG_PATH="/usr/local/etc"
CONFIG_FILE="${CONFIG_PATH}/${SCRIPTNAME}.conf"
PRD_NAME="Boot Environments Manager"
DEFAULT_ZFSBE_MANAGER="bectl"
DEFAULT_RESTORE_NAME_PREFIX="restore"
DEFAULT_COMPRESS="xz"
DEFAULT_COMPRESS_XZ="-0 -v"
DEFAULT_DECOMPRESS_XZ="-c -d -v"
DEFAULT_COMPRESS_GZ="-1 -v"
DEFAULT_DECOMPRESS_GZ="-k -d -c -v"
DEFAULT_MOUNT_POSTFIX="_BE"
ROOT_FS=$(mount | awk '/ \/ / {print $1}')
ZROOT_POOL=$(echo ${ROOT_FS} | awk -F '/' '{print $1}')
BOOT_FS=$(zpool list -H -o bootfs ${ZROOT_POOL})
ZROOT_DATASET=$(echo ${BOOT_FS} | sed 's|/[^/]*$||')
OPTION="${1}"
PARAM2="${2}"
PARAM3="${3}"

# Check if this system is Boot Environments compliant.
if echo "${ROOT_FS}" | grep -q -m 1 -E "^/dev/"; then
	echo "Error: This system does not boot from ZFS pool."
	exit 1
elif [ $(echo ${ROOT_FS} | awk -F '/' '{print NF}') -lt 3 ]; then
	echo "Error: This system is not configured for boot environments."
	exit 1
elif [ -z "${BOOT_FS}" -o "${BOOT_FS}" = "-" ]; then
	echo "Error: ZFS boot pool '${ZROOT_POOL}' has unset 'bootfs' property."
	exit 1
fi

# Create temporary file, default to /tmp.
TMPFILE=$(mktemp -q -t ${SCRIPTNAME})

# Remove temporary file on various signals.
trap "rm -f ${TMPFILE}" 0 1 2 5 15

runtime_configuration()
{
	# Generate initial configuration file.
	if [ ! -f "${CONFIG_FILE}" ]; then
		cat << EOF > ${CONFIG_FILE}
# Run-time configuration file for ${SCRIPTNAME}.
# Auto-generated file from ${SCRIPTNAME}.

# Set the preferred zfs boot environments management utility, e.g. "beadm".
ZFS_BE_MANAGER=""

# Set a custom name prefix for the restored boot environment, default is "restore-XXXX-XX-XX-XXXXXX", date is always appended.
RESTORE_NAME_PREFIX=""

# Set a custom boot environment name postfix for the mountpoint, default is "_BE".
MOUNTPOINT_NAME_POSTFIX=""

# Set the preferred compression utility, set between "xz", "gzip" or "raw"(no compress), empty defaults to xz.
COMPRESS_UTILITY=""

# Path where to save boot environments backup files, e.g. "/mnt/tank/zfsbackups".
ZFS_BACKUP_PATH=""

# Path to use for mounting boot environments, e.g. "/mnt".
ZFS_MOUNT_PATH=""

# Skip backup mode dialog, set between "local" or "remote" backup modes.  
ZFS_BACKUP_MODE=""

# Set zfs send extra parameters, e.g. "-v" default empty.
ZFS_SEND_PARAMS=""

# Set zfs receive extra parameters, e.g. "-v" default empty.
ZFS_RECV_PARAMS=""

# Set SSH parameters, e.g. "root@192.168.1.250".
SSH_NET_PARAMS=""

# Set custom compression options for XZ, e.g. "-9 -v --threads=0", empty for defaults.
XZ_COMPRESS_OPTIONS=""

# Set custom decompression options for XZ, e.g. "-c -d -v", empty for defaults.
XZ_DECOMPRESS_OPTIONS=""

# Set custom compression options for GZIP, e.g. "-9 -v", empty for defaults.
GZ_COMPRESS_OPTIONS=""

# Set custom decompression options for GZIP, e.g. "-k -d -c -v", empty for defaults.
GZ_DECOMPRESS_OPTIONS=""

# Display boot environments only and always take a recent snapshot before backup, empty to disable.
UI_SIMPLE_MODE=""
EOF

		# Start the initial configuration dialog helper.
		# Use --inputbox here to allow input scrolling.

		# Remove config file on various signals.
		trap "rm -f ${CONFIG_FILE}" 1 2 5 15

		# Ask for the full path for storing Boot Environments files.
		dialog --backtitle "${PRD_NAME} ${VERSION} for ${APP_VERSION}" --title "Boot Environments Backup Path" \
		--inputbox "Please enter the full path for storing Boot Environments files." 8 70 \
		2>${TMPFILE}
		BACKUPPATH=$(cat ${TMPFILE} | tr -d ' ' | sed 's|/*$||')

		# Ask for the full path for mounting Boot Environments.
		dialog --backtitle "${PRD_NAME} ${VERSION} for ${APP_VERSION}" --title "Boot Environments Mount Path" \
		--inputbox "Please enter the full path for mounting Boot Environments." 8 70 \
		2>${TMPFILE}
		MOUNTPATH=$(cat ${TMPFILE} | tr -d ' ' | sed 's|/*$||')

		# Ask for the ssh parameters.
		dialog --backtitle "${PRD_NAME} ${VERSION} for ${APP_VERSION}" --title "SSH Parameters" \
		--inputbox "Please enter the SSH parameters here, leave empty for none." 8 70 \
		2>${TMPFILE}
		SSHPARAMS=$(cat ${TMPFILE})

		# Ask for utility usage mode.
		dialog --backtitle "${PRD_NAME} ${VERSION} for ${APP_VERSION}" --title "Backups in simple mode" \
		--radiolist "Show boot environments only and take a recent snapshot before backup?" 10 70 4 \
		1 "Yes, Simple backup mode." on \
		2 "No, Advanced backup mode." off \
		2>${TMPFILE}
		SIMPLEMODE=$(cat ${TMPFILE})

		# Write configuration file.
		echo "Generating initial configuration..."
		if [ -n "${BACKUPPATH}" ]; then
			sysrc -f ${CONFIG_FILE} ZFS_BACKUP_PATH="${BACKUPPATH}"
		else
			echo "Error: ZFS Backup Path can't be left blank."
			rm -f ${CONFIG_FILE}
			pause
			exit 1
		fi
		if [ -n "${MOUNTPATH}" ]; then
			sysrc -f ${CONFIG_FILE} ZFS_MOUNT_PATH="${MOUNTPATH}"
		else
			echo "Error: ZFS BE Mount Path can't be left blank."
			rm -f ${CONFIG_FILE}
			pause
			exit 1
		fi
		if [ -n "${SSHPARAMS}" ]; then
			sysrc -f ${CONFIG_FILE} SSH_NET_PARAMS="${SSHPARAMS}"
		fi
		if [ "${SIMPLEMODE}" = 1 ]; then
			sysrc -f ${CONFIG_FILE} UI_SIMPLE_MODE="yes"
		elif [ "${SIMPLEMODE}" = 2 ]; then
			sysrc -f ${CONFIG_FILE} UI_SIMPLE_MODE=""
		fi
	fi
	runtime_variables
}

runtime_variables()
{
	# Initialize run-time variables once in TUI/CLI mode.
	if [ "${RUNTIMEVAR}" != 1 ]; then
		ZBE_COMMAND=$(sysrc -f ${CONFIG_FILE} -qn ZFS_BE_MANAGER)
		BE_MOUNTPATH=$(sysrc -f ${CONFIG_FILE} -qn ZFS_MOUNT_PATH)
		ZFSBACKUP_PATH=$(sysrc -f ${CONFIG_FILE} -qn ZFS_BACKUP_PATH)
		ZFSBACKUP_MODE=$(sysrc -f ${CONFIG_FILE} -qn ZFS_BACKUP_MODE)
		ZFS_SENDPARAM=$(sysrc -f ${CONFIG_FILE} -qn ZFS_SEND_PARAMS)
		ZFS_RECVPARAM=$(sysrc -f ${CONFIG_FILE} -qn ZFS_RECV_PARAMS)
		SSH_PARAMS=$(sysrc -f ${CONFIG_FILE} -qn SSH_NET_PARAMS)
		RESTORE_NAMEPREFIX=$(sysrc -f ${CONFIG_FILE} -qn RESTORE_NAME_PREFIX)
		MOUNT_POSTFIX=$(sysrc -f ${CONFIG_FILE} -qn MOUNTPOINT_NAME_POSTFIX)
		COMPRESS_UTILITY=$(sysrc -f ${CONFIG_FILE} -qn COMPRESSION_UTILITY)
		COMPRESS_OPTIONS_XZ=$(sysrc -f ${CONFIG_FILE} -qn XZ_COMPRESS_OPTIONS)
		DECOMPRESS_OPTIONS_XZ=$(sysrc -f ${CONFIG_FILE} -qn XZ_DECOMPRESS_OPTIONS)
		COMPRESS_OPTIONS_GZ=$(sysrc -f ${CONFIG_FILE} -qn GZ_COMPRESS_OPTIONS)
		DECOMPRESS_OPTIONS_GZ=$(sysrc -f ${CONFIG_FILE} -qn GZ_DECOMPRESS_OPTIONS)

		if [ -z "${RESTORE_NAMEPREFIX}" ]; then
			RESTORE_NAMEPREFIX="${DEFAULT_RESTORE_NAME_PREFIX}"
		fi

		if [ -z "${MOUNT_POSTFIX}" ]; then
			MOUNT_POSTFIX="${DEFAULT_MOUNT_POSTFIX}"
		fi

		SSH_CMD="ssh ${SSH_PARAMS}"
		UI_MODE=$(sysrc -f ${CONFIG_FILE} -qn UI_SIMPLE_MODE)
		RUNTIMEVAR=1
	fi

	# Set the be management command to use.
	if [ -z "${ZBE_COMMAND}" ]; then
		ZBE_COMMAND="${DEFAULT_ZFSBE_MANAGER}"
	fi
	APP_VERSION=$(echo ${ZBE_COMMAND})

	# Check if we have the be management command installed.
	if ! which -s ${ZBE_COMMAND}; then
		echo "Error: Required ${ZBE_COMMAND} command not found."
		exit 1
	fi
}

pause()
{
	read -p "Press enter to continue!" a
}

initialize_variables()
{
	# Always update this variables.
	BOOTENV_LIST=$(${ZBE_COMMAND} list -H | awk '{print $1}')
	#ZROOTSNAP_LIST=$(zfs list -H -r -t snapshot ${BOOT_FS} | cut -d'/' -f3 | awk '{print $1}')
	ZROOTSNAP_LIST=$(zfs list -H -r -t snapshot ${ZROOT_DATASET} | cut -d'/' -f3 | awk '{print $1}')
}

menu_activate_be()
{
	ITEM="Boot Environment"
	TOPIC="activate"

	if [ "${CLI}" = 0 ]; then
		ITEMSTATS=1
		BOOTENVLIST="${BOOTENV_LIST}"
		menu_select_be
	else
		if [ -z "${PARAM2}" ]; then
			usage
			exit 1
		fi
		BOOTENV_ITEM="${PARAM2}"
	fi

	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_ITEM} Boot Environment..."
	RETURN=1

	# Activate selected Boot Environment.
	${ZBE_COMMAND} activate ${BOOTENV_ITEM}

	RETURN=$?
	if [ "${RETURN}" -eq 0 ]; then
		msg="Boot Environment ${BOOTENV_ITEM} activated successfully!"
		echo ${msg}
		echo "Please reboot now to boot from the recently activated Boot Environment!"
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
			menu_main
		else
			exit 0
		fi
	else
		msg="Error: Unable to activate ${BOOTENV_ITEM} Boot Environment."
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
}

menu_create_be()
{
	TOPIC="create"

	if [ "${CLI}" = 0 ]; then
		TITLE="\nPlease enter a valid Boot Environment name here for your reference."
		menu_be_name
	else
		if [ -z "${PARAM2}" ]; then
			usage
			exit 1
		fi
		BOOTENV_NAME="${PARAM2}"
	fi

	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_NAME} Boot Environment..."
	RETURN=1

	# Create new Boot Environment.
	${ZBE_COMMAND} create ${BOOTENV_NAME}

	RETURN=$?
	if [ "${RETURN}" -eq 0 ]; then
		msg="Boot Environment ${BOOTENV_NAME} created successfully!"
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
			menu_main
		else
			exit 0
		fi
	else
		msg="Error: Unable to create ${BOOTENV_NAME} Boot Environment."
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
}

menu_mount_be()
{
	ITEM="Boot Environment"
	TOPIC="mount"

	if [ "${CLI}" = 0 ]; then
		ITEMSTATS=1
		BOOTENVLIST="${BOOTENV_LIST}"
		menu_select_be
	else
		if [ -z "${PARAM2}" ]; then
			usage
			exit 1
		fi
		BOOTENV_ITEM="${PARAM2}"
	fi

	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_ITEM} Boot Environment..."

	DIR="${BE_MOUNTPATH}/${BOOTENV_ITEM}${MOUNT_POSTFIX}"
	if ! mount | grep -q ${DIR}; then
		mkdir -p ${DIR}
		RETURN=1

		# Mount selected Boot Environment.
		${ZBE_COMMAND} mount ${BOOTENV_ITEM} ${DIR} && chmod 0700 ${DIR}

		RETURN=$?
		if [ "${RETURN}" -eq 0 ]; then
			msg="Boot Environment ${BOOTENV_ITEM} mounted successfully!"
			echo ${msg}
			/usr/bin/logger -t ${SCRIPTNAME} ${msg}
			if [ "${CLI}" = 0 ]; then
				pause
				menu_main
			else
				exit 0
			fi
		else
			msg="Error: Unable to mount ${BOOTENV_ITEM} Boot Environment."
			echo ${msg}
			/usr/bin/logger -t ${SCRIPTNAME} ${msg}
			if [ ! $(ls -A ${DIR} 2>/dev/null) ]; then
				# Delete directory only if empty.
				rm -Rf ${DIR}
			fi
			if [ "${CLI}" = 0 ]; then
				pause
			fi
			exit 1
		fi
	else
		echo "Mount ${DIR} already exist."
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
}

menu_umount_be()
{
	ITEM="Boot Environment"
	TOPIC="unmount"

	if [ "${CLI}" = 0 ]; then
		ITEMSTATS=1
		BOOTENVLIST="${BOOTENV_LIST}"
		menu_select_be
	else
		if [ -z "${PARAM2}" ]; then
			usage
			exit 1
		fi
		BOOTENV_ITEM="${PARAM2}"
	fi

	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_ITEM} Boot Environment..."

	DIR="${BE_MOUNTPATH}/${BOOTENV_ITEM}${MOUNT_POSTFIX}"
	if [ -d "${DIR}" ]; then
		RETURN=1

		# Unmount selected Boot Environment.
		${ZBE_COMMAND} umount -f ${BOOTENV_ITEM}

		RETURN=$?
		if [ "${RETURN}" -eq 0 ]; then
			if [ ! $(ls -A ${DIR} 2>/dev/null) ]; then
				# Delete directory only if empty.
				rm -Rf ${DIR}
			fi
			msg="Boot Environment ${BOOTENV_ITEM} unmounted successfully!"
			echo ${msg}
			/usr/bin/logger -t ${SCRIPTNAME} ${msg}
			if [ "${CLI}" = 0 ]; then
				pause
				menu_main
			else
				exit 0
			fi
		else
			msg="Error: Unable to unmount ${BOOTENV_ITEM} Boot Environment."
			echo ${msg}
			/usr/bin/logger -t ${SCRIPTNAME} ${msg}
			if [ "${CLI}" = 0 ]; then
				pause
			fi
			exit 1
		fi
	else
		echo "Mount ${DIR} does not exist."
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
}

menu_rename_be()
{
	ITEM="Boot Environment"
	TOPIC="rename"

	if [ "${CLI}" = 0 ]; then
		ITEMSTATS=1
		BOOTENVLIST="${BOOTENV_LIST}"
		menu_select_be
		TITLE="\nPlease enter a new Boot Environment name for ${BOOTENV_ITEM}."
		menu_be_name
	else
		if [ -z "${PARAM2}" ] || [ -z "${PARAM3}" ]; then
			usage
			exit 1
		fi
		BOOTENV_ITEM="${PARAM2}"
		BOOTENV_NAME="${PARAM3}"
	fi

	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_ITEM} Boot Environment..."
	RETURN=1

	# Rename selected Boot Environment.
	${ZBE_COMMAND} rename ${BOOTENV_ITEM} ${BOOTENV_NAME}

	RETURN=$?
	if [ "${RETURN}" -eq 0 ]; then
		msg="Boot Environment ${BOOTENV_ITEM} renamed to ${BOOTENV_NAME} successfully!"
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
			menu_main
		else
			exit 0
		fi
	else
		msg="Error: Unable to rename ${BOOTENV_ITEM} Boot Environment."
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
	
}

menu_backup_be()
{
	TOPIC="backup"

	if [ "${CLI}" = 0 ]; then
		# Ask for backup mode and check directory.
		menu_backup_mode
		backup_dir_check

		# Check if simple backup mode is enabled.
		if [ "${UI_MODE}" = "yes" -o "${UI_MODE}" = "YES" ]; then
			ITEM="Boot Environment"
			ITEMSTATS=1
			BOOTENVLIST="${BOOTENV_LIST}"
		else
			ITEM="Boot Environment@Snapshot"
			ITEMSTATS=0
			BOOTENVLIST="${ZROOTSNAP_LIST}"
		fi

		menu_select_be
	else
		# Check for user defined parameters.
		if [ -z "${PARAM3}" ]; then
			PARAM3="${ZFSBACKUP_MODE}"
		fi
		if [ -z "${PARAM2}" ] || [ -z "${PARAM3}" ]; then
			usage
			exit 1
		fi
		if [ "${PARAM3}" = "local" ]; then
			BACKUP_MODE=1
		elif [ "${PARAM3}" = "remote" ]; then
			BACKUP_MODE=2
		else
			echo "Error: Unknown backup target location."
			exit 1
		fi
		backup_dir_check
		BOOTENV_ITEM="${PARAM2}"
	fi

	# Set the compression utility.
	case "${COMPRESS_UTILITY}" in
		gz|GZ|gzip|GZIP)
			COMPRESS_METHOD="gz"
			ARCHIVE_EXT=".gz"
			;;
		xz|XZ)
			COMPRESS_METHOD="xz"
			ARCHIVE_EXT=".xz"
			;;
		raw|RAW)
			COMPRESS_METHOD="raw"
			ARCHIVE_EXT=""
			;;
		*)
			COMPRESS_METHOD="xz"
			ARCHIVE_EXT=".xz"
			;;
	esac

	# Check if simple backup mode is enabled.
	if [ "${UI_MODE}" = "yes" -o "${UI_MODE}" = "YES" ]; then
		TOPIC2="snapshot"
		get_current_date
		echo
		echo "=> Attempting to ${TOPIC2} ${BOOTENV_ITEM} Boot Environment..."
		RETURN=1

		# Temporary snapshot selected Boot Environment
		${ZBE_COMMAND} create ${BOOTENV_ITEM}@${DATE}

		RETURN=$?
		if [ "${RETURN}" -eq 0 ]; then
			msg="Boot Environment ${BOOTENV_ITEM} ${TOPIC2} successfully!"
			echo ${msg}
			/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		else
			msg="Error: Unable to ${TOPIC2} ${BOOTENV_ITEM} Boot Environment."
			echo ${msg}
			/usr/bin/logger -t ${SCRIPTNAME} ${msg}
			exit 1
		fi
		# Send compressed be/snapshot to file.
		BE_SOURCE="${ZROOT_DATASET}/${BOOTENV_ITEM}@${DATE}"
		BE_TARGET="${ZFSBACKUP_PATH}/${BOOTENV_ITEM}-${DATE}${ARCHIVE_EXT}"
		BACKUPNAME="${BOOTENV_ITEM}-${DATE}${ARCHIVE_EXT}"
	else
		generate_backup_name
		# Send compressed be/snapshot to file.
		BE_SOURCE="${ZROOT_DATASET}/${BOOTENV_ITEM}"
		BE_TARGET="${ZFSBACKUP_PATH}/${BEBACKUP_NAME}"
		BACKUPNAME="${BEBACKUP_NAME}"
	fi

	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_ITEM} Boot Environment..."
	RETURN=1

	# Set the compression method/options.
	if [ "${COMPRESS_METHOD}" = "xz" ]; then
		if [ -z "${COMPRESS_OPTIONS_XZ}" ]; then
			COMPRESS_OPTIONS_XZ="${DEFAULT_COMPRESS_XZ}"
		fi
	elif [ "${COMPRESS_METHOD}" = "gz" ]; then
		if [ -z "${COMPRESS_OPTIONS_GZ}" ]; then
			COMPRESS_OPTIONS_GZ="${DEFAULT_COMPRESS_GZ}"
		fi
	fi

	if [ "${BACKUP_MODE}" = 1 ]; then
		# Local backup target file.
		if [ "${COMPRESS_METHOD}" = "xz" ]; then
			zfs send ${ZFS_SENDPARAM} ${BE_SOURCE} | xz ${COMPRESS_OPTIONS_XZ} > ${BE_TARGET}
		elif [ "${COMPRESS_METHOD}" = "gz" ]; then
			zfs send ${ZFS_SENDPARAM} ${BE_SOURCE} | gzip ${COMPRESS_OPTIONS_GZ} > ${BE_TARGET}
		elif [ "${COMPRESS_METHOD}" = "raw" ]; then
			zfs send ${ZFS_SENDPARAM} ${BE_SOURCE} > ${BE_TARGET}
		fi
	elif [ "${BACKUP_MODE}" = 2 ]; then
		# Network backup target file.
		echo "Saving to network location, this might take a while please wait..."
		if [ "${COMPRESS_METHOD}" = "xz" ]; then
			zfs send ${ZFS_SENDPARAM} ${BE_SOURCE} | ${SSH_CMD} "xz ${COMPRESS_OPTIONS_XZ} > ${BE_TARGET}"
		elif [ "${COMPRESS_METHOD}" = "gz" ]; then
			zfs send ${ZFS_SENDPARAM} ${BE_SOURCE} | ${SSH_CMD} "gzip ${COMPRESS_OPTIONS_GZ} > ${BE_TARGET}"
		elif [ "${COMPRESS_METHOD}" = "raw" ]; then
			zfs send ${ZFS_SENDPARAM} ${BE_SOURCE} | ${SSH_CMD} "cat > ${BE_TARGET}"
		fi
	fi

	RETURN=$?
	if [ "${RETURN}" -eq 0 ]; then
		msg="Boot Environment ${BOOTENV_ITEM} saved to ${ZFSBACKUP_PATH}/${BACKUPNAME} successfully!"
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}

		# Remove temporary snapshot on success on simple mode.
		if [ "${UI_MODE}" = "yes" -o "${UI_MODE}" = "YES" ]; then
			TOPIC="snapshot"
			echo
			echo "=> Attempting to cleanup recent ${BOOTENV_ITEM} Boot Environment ${TOPIC}..."
			RETURN=1

			zfs destroy ${ZROOT_DATASET}/${BOOTENV_ITEM}@${DATE}

			RETURN=$?
			if [ "${RETURN}" -eq 0 ]; then
				msg="Boot Environment ${BOOTENV_ITEM} recent ${TOPIC} cleaned successfully!"
				echo ${msg}
				/usr/bin/logger -t ${SCRIPTNAME} ${msg}
			else
				msg="Error: Unable to cleanup ${BOOTENV_ITEM} recent Boot Environment ${TOPIC}."
				echo ${msg}
				/usr/bin/logger -t ${SCRIPTNAME} ${msg}
				exit 1
			fi
		fi

		if [ "${CLI}" = 0 ]; then
			pause
			menu_main
		else
			exit 0
		fi
	else
		msg="Error: Unable to ${TOPIC} ${BOOTENV_ITEM} Boot Environment."
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
}

menu_restore_be()
{
	ITEM="Boot Environment file"
	TOPIC="restore"
	RESTORE_NAME="${RESTORE_NAMEPREFIX}"

	if [ "${CLI}" = 0 ]; then
		# Ask for backup mode and check directory.
		menu_backup_mode
		backup_dir_check

		ITEMSTATS=0
		BOOTENVLIST="${ZFSBACKUP_DIR}"
		menu_select_be
	else
		# Check for user defined parameters.
		if [ -z "${PARAM3}" ]; then
			PARAM3="${ZFSBACKUP_MODE}"
		fi
		if [ -z "${PARAM2}" ] || [ -z "${PARAM3}" ]; then
			usage
			exit 1
		fi
		if [ "${PARAM3}" = "local" ]; then
			BACKUP_MODE=1
		elif [ "${PARAM3}" = "remote" ]; then
			BACKUP_MODE=2
		else
			echo "Error: Unknown backup source location."
			exit 1
		fi
		backup_dir_check
		BOOTENV_ITEM="${PARAM2}"
	fi

	get_current_date

	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_ITEM} from file..."
	RETURN=1

	# Receive compressed be/snapshot from file.
	BE_SOURCE="${ZFSBACKUP_PATH}/${BOOTENV_ITEM}"
	BE_TARGET="${ZROOT_DATASET}/${RESTORE_NAME}-${DATE}@${DATE}"

	# Set the decompression method/options.
	case "${BOOTENV_ITEM}" in
		*.xz)
			DECOMPRESS_METHOD="xz"
			if [ -z "${DECOMPRESS_OPTIONS_XZ}" ]; then
				DECOMPRESS_OPTIONS_XZ="${DEFAULT_DECOMPRESS_XZ}"
			fi
			;;
		*.gz)
			DECOMPRESS_METHOD="gz"
			if [ -z "${DECOMPRESS_OPTIONS_GZ}" ]; then
				DECOMPRESS_OPTIONS_GZ="${DEFAULT_DECOMPRESS_GZ}"
			fi
			;;
		*.zfs)
			# This is for backward compatibility with previous versions, may be deprecated soon.
			DECOMPRESS_METHOD="xz"
			if [ -z "${DECOMPRESS_OPTIONS_XZ}" ]; then
				DECOMPRESS_OPTIONS_XZ="${DEFAULT_DECOMPRESS_XZ}"
			fi
			;;
		*)
			DECOMPRESS_METHOD="raw"
			;;
	esac

	if [ "${BACKUP_MODE}" = 1 ]; then
		# Local restore from file.
		if [ "${DECOMPRESS_METHOD}" = "xz" ]; then
			xz ${DECOMPRESS_OPTIONS_XZ} ${BE_SOURCE} | zfs receive ${ZFS_RECVPARAM} ${BE_TARGET}
		elif [ "${DECOMPRESS_METHOD}" = "gz" ]; then
			gzip ${DECOMPRESS_OPTIONS_GZ} ${BE_SOURCE} | zfs receive ${ZFS_RECVPARAM} ${BE_TARGET}
		elif [ "${DECOMPRESS_METHOD}" = "raw" ]; then
			zfs receive ${ZFS_RECVPARAM} ${BE_TARGET} < ${BE_SOURCE}
		fi
	elif [ "${BACKUP_MODE}" = 2 ]; then
		# Remote restore from file.
		echo "Restoring from network location, this might take a while please wait..."
		if [ "${DECOMPRESS_METHOD}" = "xz" ]; then
			${SSH_CMD} "xz ${DECOMPRESS_OPTIONS_XZ} ${BE_SOURCE}" | zfs receive ${ZFS_RECVPARAM} ${BE_TARGET}
		elif [ "${DECOMPRESS_METHOD}" = "gz" ]; then
			${SSH_CMD} "gzip ${DECOMPRESS_OPTIONS_GZ} ${BE_SOURCE}" | zfs receive ${ZFS_RECVPARAM} ${BE_TARGET}
		elif [ "${DECOMPRESS_METHOD}" = "raw" ]; then
			${SSH_CMD} "cat < ${BE_SOURCE}" | zfs receive ${ZFS_RECVPARAM} ${BE_TARGET}
		fi
	fi

	RETURN=$?
	if [ "${RETURN}" -eq 0 ]; then
		msg="Boot Environment ${BOOTENV_ITEM} restored to ${ZROOT_DATASET}/${RESTORE_NAME}-${DATE} successfully!"
		echo ${msg}
		echo "=> Activate the restored Boot Environment for it to take effect after reboot!"
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
			menu_main
		else
			exit 0
		fi
	else
		msg="Error: Unable to restore ${BOOTENV_ITEM} Boot Environment."
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
}

menu_snapshot_be()
{
	ITEM="Boot Environment"
	TOPIC="snapshot"

	if [ "${CLI}" = 0 ]; then
		ITEMSTATS=1
		BOOTENVLIST="${BOOTENV_LIST}"
		menu_select_be
	else
		if [ -z "${PARAM2}" ]; then
			usage
			exit 1
		fi
		BOOTENV_ITEM="${PARAM2}"
	fi

	get_current_date
	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_ITEM} Boot Environment..."
	RETURN=1

	# Snapshot selected Boot Environment.
	${ZBE_COMMAND} create ${BOOTENV_ITEM}@${DATE}

	RETURN=$?
	if [ "${RETURN}" -eq 0 ]; then
		msg="Boot Environment ${BOOTENV_ITEM} ${TOPIC} successfully!"
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
			menu_main
		else
			exit 0
		fi
	else
		msg="Error: Unable to ${TOPIC} ${BOOTENV_ITEM} Boot Environment."
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
}

menu_destroy_be()
{
	ITEM="Boot Environment"
	TOPIC="destroy"

	if [ "${CLI}" = 0 ]; then
		ITEMSTATS=1
		BOOTENVLIST="${BOOTENV_LIST}"
		menu_select_be
	else
		if [ -z "${PARAM2}" ]; then
			usage
			exit 1
		fi
		BOOTENV_ITEM="${PARAM2}"
	fi

	echo
	echo "=> Attempting to ${TOPIC} ${BOOTENV_ITEM} Boot Environment..."
	RETURN=1

	# Destroy the selected Boot Environment.
	${ZBE_COMMAND} destroy -F ${BOOTENV_ITEM}

	RETURN=$?
	if [ "${RETURN}" -eq 0 ]; then
		msg="Boot Environment ${BOOTENV_ITEM} destroyed successfully!"
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
			menu_main
		else
			exit 0
		fi
	else
		msg="Error: Unable to destroy ${BOOTENV_ITEM} Boot Environment."
		echo ${msg}
		/usr/bin/logger -t ${SCRIPTNAME} ${msg}
		if [ "${CLI}" = 0 ]; then
			pause
		fi
		exit 1
	fi
}

backup_dir_check()
{
	# Check if the backup directory has been defined and is accessible.
	if [ "${BACKUP_MODE}" = 1 ]; then
		if [ -z "${ZFSBACKUP_PATH}" ]; then
			echo "Error: ZFS BE backup directory is undefined."
			echo "Please check ${CONFIG_FILE} file."
			exit 1
		elif [ ! -d "${ZFSBACKUP_PATH}" ]; then
			echo "Error: ZFS BE backup directory not found."
			echo "Please make sure the backup path exist and is accessible."
			exit 1
		fi
		ZFSBACKUP_DIR=$(ls ${ZFSBACKUP_PATH} | grep -E ".gz$|.xz$|.zfs$|-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}$" || true)
	elif [ "${BACKUP_MODE}" = 2 ]; then
		if [ -z "${SSH_PARAMS}" ]; then
			echo "Error: SSH parameters are undefined."
			echo "Please check ${CONFIG_FILE} file."
			exit 1
		else
			NETWORK_PATH=$(${SSH_CMD} "ls ${ZFSBACKUP_PATH} >/dev/null"; echo $?)
			if [ "${NETWORK_PATH}" != 0 ]; then
				echo "Error: Network path not found."
				echo "Please make sure the network path exist and is accessible on the remote host."
				exit 1
			else
				ZFSBACKUP_DIR=$(${SSH_CMD} "ls ${ZFSBACKUP_PATH}" | grep -E ".gz$|.xz$|.zfs$|-[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6}$" || true)
			fi
		fi
	fi
}

generate_backup_name()
{
	# Generate the backup file name based on the seleted Boot Environment.
	get_current_date
	BENAME=$(echo ${BOOTENV_ITEM} | cut -d"@" -f1 | awk '{print $1}')
	BEBACKUP_NAME="${BENAME}-${DATE}${ARCHIVE_EXT}"
}

get_current_date()
{
	# Get current date and time.
	DATE=$(date +%F-%H%M%S)
}

menu_backup_mode()
{
	# Check for user defined parameters.
	if [ "${ZFSBACKUP_MODE}" = "local" ]; then
		BACKUP_MODE=1
	elif [ "${ZFSBACKUP_MODE}" = "remote" ]; then
		BACKUP_MODE=2
	else
		BACKUP_MODE=""
	fi

	if [ -z "${BACKUP_MODE}" ]; then
		# Ask for the backup mode.
		dialog --backtitle "${PRD_NAME} ${VERSION} for ${APP_VERSION}" --title "Backup location selection menu" \
		--radiolist "Select the backup location, default is Local." 10 50 4 \
		1 "Local System Backup" on \
		2 "Remote System Backup" off \
		2>${TMPFILE}
		if [ $? -ne 0 ]; then
			exit 0
		fi
		BACKUP_MODE=$(cat ${TMPFILE})
	fi	
}

get_be_status()
{
	# Get Boot Environments status information.
	BOOTENV_STATUS=$(${ZBE_COMMAND} list -H | awk '{ print $1,$2,$3,$5 }' | grep -F ${BE} | awk '{ print $2,$3,$4 }')
}

get_be_list()
{
	# List Boot Environments.
	VAL=""
	local BE
	for BE in ${BOOTENVLIST}; do
		VAL="${VAL} ${BE}"
	done
	VAL=$(echo ${VAL} | tr ' ' '\n')
}

menu_select_be()
{
	# Build the Boot Environments menu.
	get_be_list
	BE="${VAL}"
	list=""
	items=0
	for BE in ${BE}; do
		if [ "${ITEMSTATS}" != 0 ]; then
			get_be_status ${BE}
			desc="Status: ${BOOTENV_STATUS}"
			list="${list} ${BE} '${desc}' off"
		else
			list="${list} ${BE} '' off"
		fi
		items=$((${items} + 1))
	done

	if [ "${items}" -ge 10 ]; then
		items=10
		menuheight=20
	else
		menuheight=10
		menuheight=$((${menuheight} + ${items}))
	fi

	if [ "${items}" -eq 0 ]; then
		eval "dialog --title 'Select ${ITEM}' --msgbox 'No ${ITEM} available!' 5 60" \
		2>${TMPFILE}
		exit 1
	fi

	eval "dialog --backtitle '${PRD_NAME} ${VERSION} for ${APP_VERSION}' --title 'Select Boot Environment' \
		--radiolist 'Select any ${ITEM} you wish to ${TOPIC}, use [up] [down] keys to navigate the menu then select a item with the [spacebar].' \
		${menuheight} 80 ${items} ${list}" \
		2>${TMPFILE}
	if [ $? -ne 0 ]; then
		exit 0
	fi

	BOOTENV_ITEM=$(cat ${TMPFILE})
	if [ -z "${BOOTENV_ITEM}" ]; then
		menu_select_be
	fi
}

menu_be_name()
{
	# Ask for new Boot Environment name.
	dialog --backtitle "${PRD_NAME} ${VERSION} for ${APP_VERSION}" --title "Boot Environment Name" \
	--inputbox "${TITLE}" 8 70 \
	2>${TMPFILE}
	if [ $? -ne 0 ]; then
		exit 0
	fi

	BOOTENV_NAME=$(cat ${TMPFILE} | tr -d ' ')
	if [ -z "${BOOTENV_NAME}" ]; then
		menu_be_name
	fi
}

menu_main()
{
	# Initialize variables and display the main menu.
	CLI=0
	runtime_configuration
	initialize_variables

	while :; do
		dialog --backtitle "${PRD_NAME} ${VERSION} for ${APP_VERSION}" --clear --title "Boot Environments Manager" --cancel-label "Exit" --menu "" 15 50 10 \
		"1" "Activate Boot Environment" \
		"2" "Create Boot Environment" \
		"3" "Mount Boot Environment" \
		"4" "Unmount Boot Environment" \
		"5" "Rename Boot Environment" \
		"6" "Backup Boot Environment" \
		"7" "Restore Boot Environment" \
		"8" "Snapshot Boot Environment" \
		"9" "Destroy Boot Environment" \
		2>${TMPFILE}
		if [ $? -ne 0 ]; then
			exit 0
		fi
		choice=$(cat "${TMPFILE}")
		case "${choice}" in
			1) menu_activate_be;;
			2) menu_create_be;;
			3) menu_mount_be;;
			4) menu_umount_be;;
			5) menu_rename_be;;
			6) menu_backup_be;;
			7) menu_restore_be;;
			8) menu_snapshot_be;;
			9) menu_destroy_be;;
		esac
	done
}

if [ -n "${OPTION}" ]; then
	# Initialize variables and execute command.
	CLI=1
	runtime_configuration

	case "${OPTION}" in
		-a|--activate) menu_activate_be;;
		-c|--create) menu_create_be;;
		-m|--mount) menu_mount_be;;
		-u|--umount) menu_umount_be;;
		-n|--rename) menu_rename_be;;
		-b|--backup) menu_backup_be;;
		-r|--restore) menu_restore_be;;
		-s|--snapshot) menu_snapshot_be;;
		-d|--destroy) menu_destroy_be;;
		*) echo "Invalid option, -h for usage."; exit 1;;
	esac
fi
menu_main
